/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminDestaquesRouteImport } from './routes/admin.destaques'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOfertasRouteImport } from './routes/admin.ofertas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as ProdutoHandleRouteImport } from './routes/produto.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestaquesRoute = AdminDestaquesRouteImport.update({
  id: '/destaques',
  path: '/destaques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfertasRoute = AdminOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoHandleRoute = ProdutoHandleRouteImport.update({
  id: '/produto/$handle',
  path: '/produto/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/produto/$handle': typeof ProdutoHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/banners'
    | '/admin/destaques'
    | '/admin/login'
    | '/admin/ofertas'
    | '/admin/produtos'
    | '/produto/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/banners'
    | '/admin/destaques'
    | '/admin/login'
    | '/admin/ofertas'
    | '/admin/produtos'
    | '/produto/$handle'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/banners'
    | '/admin/destaques'
    | '/admin/login'
    | '/admin/ofertas'
    | '/admin/produtos'
    | '/produto/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProdutoHandleRoute: typeof ProdutoHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destaques': {
      id: '/admin/destaques'
      path: '/destaques'
      fullPath: '/admin/destaques'
      preLoaderRoute: typeof AdminDestaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ofertas': {
      id: '/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AdminOfertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$handle': {
      id: '/produto/$handle'
      path: '/produto/$handle'
      fullPath: '/produto/$handle'
      preLoaderRoute: typeof ProdutoHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDestaquesRoute: typeof AdminDestaquesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOfertasRoute: typeof AdminOfertasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDestaquesRoute: AdminDestaquesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOfertasRoute: AdminOfertasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProdutoHandleRoute: ProdutoHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
